apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: analysis-service
    version: {{ .Chart.AppVersion | default "1.0" }}
data:
  application.yml: |
    server:
      port: {{ .Values.config.server.port | default 8080 }}
    spring:
      application:
        name: {{ .Values.config.app.name | default "analysis-service" }}
      datasource:
        driver-class-name: {{ .Values.config.datasource.driverclassname | default "com.mysql.cj.jdbc.Driver"}}
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: {{ .Values.config.jpa.hibernate.ddlauto | default "update" }}
        properties:
          format_sql: {{ .Values.config.jpa.properties.formatsql | default "true" }}
        show-sql: {{ .Values.config.jpa.showsql | default "true" }}
    aws:
      region: ${AWS_REGION}
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
      athena:
        database: {{ .Values.config.aws.athena.database | default "drive"}}
        output-location: ${ATHENA_OUTPUT_LOCATION}
    management:
      endpoints:
        web:
          exposure:
            include: "*"
