{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # ✅ 올바른 함수 호출 방식
  name: {{ .Chart.Name }}-hpa
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  scaleTargetRef:
    kind: Deployment
    # ✅ deployment.yaml과 일관성 유지
    name: {{ .Chart.Name }}
    apiVersion: apps/v1

  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}

  # ✅ 메모리 메트릭만 사용
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.metric.utilization.memoryAverage }}

  # 메모리 기반 스케일링 정책
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - periodSeconds: 60
          type: Percent
          value: 100
        - periodSeconds: 60
          type: Pods
          value: 2
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 120
          type: Percent
          value: 25
      selectPolicy: Min
{{- end }}
