replicaCount: 2

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/analysis-service
  tag: 20250613-744bdde
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# 헬스체크 설정
healthCheck:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 90
  periodSeconds: 10

# Analysis Service Config
config:
  server:
    port: 8080
  app:
    name: analysis-service
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 30000
    driverclassname: com.mysql.cj.jdbc.Driver
  aws:
    athena:
      database: drive
  jpa:
    hibernate:
      ddlauto: validate
    properties:
      default_batch_fetch_size: 100
      jdbc:
        batch_size: 50
        time_zone: UTC
      connection:
        provider_disables_autocommit: true
    showsql: false
    open-in-view: false

# HPA 설정 (메모리 기준)
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  metric:
    utilization:
      memoryAverage: 75

# ✅ 리소스 설정 수정 (오타 제거)
resources:
  requests:
    memory: "800Mi"
  limits:
    memory: "1Gi"  # ✅ 오타 수정: "1024mMi" → "2Gi"
