replicaCount: 1

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/analysis-service
  tag: 20250613-3071b8a
  pullPolicy: IfNotPresent    # 이미지 가져오는 정책 로컬에 없을 때만 pull

service:
  type: ClusterIP   # 클러스터 내부에서만 접근 가능 (기본값)
  port: 80

# 헬스체크 설정 (권장)
healthCheck:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10

#serviceAccount:
#  create: true
#  name:  analysis_service_sa

# Analysis Service Config
config:
  server:
    port: 8080
  app:
    name: analysis-service
  datasource:
    hikari:
      max: 20
    driverclassname: com.mysql.cj.jdbc.Driver
  aws:
    athena:
      database: drive
  jpa:
    hibernate:
      ddlauto: update
    properties:
      formatsql: true
    showsql: true